Repository LexaLukovka/partymakerFrontend, pull requests merged in 2018-08, with the labels that each got.

#46 add new aliases
  webpack.config.js
Labels: enhancement

#53 add animation
  package-lock.json
  package.json
  src/components/@party/PartyScene.jsx
  src/components/@party/style.css
  src/components/@patry-create/GeneralForm/index.jsx
  src/components/@patry-create/SummaryForm/index.jsx
Labels: enhancement

#55 fix bug with hegiht and fix blank picture on parties
  src/components/@parties/PartiesCard/index.jsx
  src/components/@party/PartyScene.jsx
Labels: bug

#68 change drawer
  src/components/Drawer/index.jsx
Labels: enhancement

#75 refactor header
  src/components/@parties/PartiesCard/index.jsx
  src/components/@parties/connector.js
  src/components/@party/PartyScene.jsx
  src/components/@patry-create/CreateLayout.jsx
  src/components/Header/UserMenu.jsx
  src/components/Header/connector.js
  src/components/Header/index.jsx
  src/redux/header/action.js
  src/redux/header/reducer.js
  src/utils/shortTitle.js
  src/utils/titleSubs.js
  webpack.config.js
Labels: refactor

#79 refactor PartyCard
  src/components/@party/PartyCard/index.jsx
  src/components/@party/PartyScene.jsx
Labels: refactor

#87 add party location on the map
  src/components/@party/PartyCard/ListItem.jsx
  src/components/@party/PartyCard/index.jsx
  src/components/@party/PartyScene.jsx
  src/components/Container/index.jsx
Labels: task

#119 fix webpack hot reloading
  webpack.config.js
Labels: bug

#128 remove @material/icons
  .babelrc
  package.json
  src/components/@auth/@login/LoginForm/index.jsx
  src/components/@auth/@register/RegisterForm/index.jsx
  src/components/@parties/@create/CreateLayout.jsx
  src/components/@parties/@create/SummaryForm/PictureUpload/PictureList.jsx
  src/components/@parties/PartiesScene/PartiesList/PartiesCard/MyCardActions.jsx
  src/components/@parties/PartiesScene/PartiesList/PartiesCard/MyCardHeader.jsx
  src/components/Alert/index.jsx
  src/components/Drawer/DrawerMenu/index.jsx
  src/components/Header/UserMenu.jsx
  src/components/Header/index.jsx
  webpack.config.prod.js
Labels: task

#136 add avatar picture to drawer
  src/components/Drawer/DrawerMenu/index.jsx
Labels: enhancement

#148 add action button
  src/components/@auth/AuthLayout.jsx
  src/components/@parties/@create/@step1/TagList.jsx
  src/components/@parties/@create/@step1/TypeScene.jsx
  src/components/@parties/@create/@step1/TypeTag.jsx
  src/components/@parties/@create/@step2/AddressInput.jsx
  src/components/@parties/@create/@step2/DayInput.jsx
  src/components/@parties/@create/@step2/DescriptionInput.jsx
  src/components/@parties/@create/@step2/DistrictInput.jsx
  src/components/@parties/@create/@step2/GeneralScene.jsx
  src/components/@parties/@create/@step2/PeopleInput.jsx
  src/components/@parties/@create/@step2/PlaceInput.jsx
  src/components/@parties/@create/@step2/TimeInput.jsx
  src/components/@parties/@create/@step2/TitleInput.jsx
  src/components/@parties/@create/CreateLayout.jsx
  src/components/@parties/@create/connector.js
  src/components/@parties/PartiesScene/connector.js
  src/components/@parties/PartiesScene/index.jsx
  src/components/@places/@place/PlaceCard/index.jsx
  src/components/@places/@place/PlaceScene.jsx
  src/components/@places/@place/connector.js
  src/components/ActionButton/connector.js
  src/components/ActionButton/index.jsx
  src/components/AndDevider/index.jsx
  src/components/Header/UserMenu.jsx
  src/components/Header/index.jsx
  src/components/LayoutScene.jsx
  src/redux/actionButton/action.js
  src/redux/actionButton/reducer.js
  src/redux/index.js
  src/redux/party/index.js
  src/redux/party/types/action.js
  src/redux/party/types/reducer.js
  src/redux/place/index.js
  src/redux/place/single/action.js
  src/redux/place/single/reducer.js
Labels: enhancement

#154 fix create party
  src/components/@parties/@create/@step2/GeneralScene.jsx
  src/components/@parties/@create/@step3/SummaryScene.jsx
  src/components/@parties/@create/CreateLayout.jsx
  src/components/@parties/PartiesLayout.jsx
  src/components/LayoutScene.jsx
  src/index.html
  src/services/api/Party.js
Labels: bug

#157 add rating to places
  package.json
  src/components/@places/@place/Parties/index.jsx
  src/components/@places/@place/PlaceCard/index.jsx
  src/components/@places/@place/PlaceScene.jsx
  src/components/@places/@place/connector.js
  src/components/@places/PlacesLayout.jsx
  src/index.js
  src/redux/place/index.js
  src/redux/place/single/reducer.js
  src/redux/place/votes/action.js
  src/redux/place/votes/reducer.js
  src/services/api/Place.js
  src/store.js
Labels: task

#158 add Desktop version
  src/components/@index/IndexScene.jsx
  src/components/@parties/@create/@step1/TypeScene.jsx
  src/components/@parties/@create/@step2/GeneralScene.jsx
  src/components/@parties/@create/@step3/SummaryScene.jsx
  src/components/@parties/@party/PartyCard/index.jsx
  src/components/@parties/@party/PartyScene.jsx
  src/components/@parties/PartiesScene/PartiesList/PartiesCard/index.jsx
  src/components/@parties/PartiesScene/PartiesList/index.jsx
  src/components/@parties/PartiesScene/index.jsx
  src/components/@places/@place/Parties/index.jsx
  src/components/@places/@place/PlaceCard/index.jsx
  src/components/@places/PlacesScene/PlacesList/PlacesCard/index.jsx
  src/components/@places/PlacesScene/index.jsx
  src/components/@users/UsersScene/Parties.jsx
  src/components/@users/UsersScene/index.jsx
  src/components/Container/index.jsx
  src/components/Header/UserMenu.jsx
  src/components/Header/index.jsx
  src/redux/header/reducer.js
Labels: task

#164 update places layout
  src/components/@places/@place/PlaceCard/index.jsx
  src/components/@places/@place/PlaceScene.jsx
  src/components/@places/@place/connector.js
  src/components/@places/PlacesScene/PlacesList/PlacesCard/index.jsx
  src/components/@places/PlacesScene/index.jsx
  src/components/Carousel/index.jsx
Labels: task

#168 update place scene
  src/components/@places/@place/PictureGrid.jsx
  src/components/@places/@place/PlaceCard/index.jsx
  src/components/@places/@place/PlaceScene.jsx
  src/components/@places/@place/connector.js
  src/components/ActionButton/index.jsx
  src/components/Container/index.jsx
  src/components/Header/index.jsx
  src/components/LayoutScene.jsx
  src/components/PictureModal/connector.js
  src/components/PictureModal/index.jsx
  src/redux/actionButton/reducer.js
  src/redux/index.js
  src/redux/pictureModal/action.js
  src/redux/pictureModal/reducer.js
  src/utils/withTheme.jsx
Labels: enhancement

#170 Refactor tokens
  src/components/@parties/@party/@edit/@image/PictureUpload/PictureList.jsx
  src/components/@parties/@party/PartyScene.jsx
  src/components/@parties/PartiesLayout.jsx
  src/components/@places/@place/PlaceCard/index.jsx
  src/components/@users/UserLayout.jsx
  src/components/Header/index.jsx
  src/services/Http.js
  src/services/api/Auth.js
Labels: refactor

#180 add password reset
  src/components/@settings/@password/formik.js
Labels: task
